version: '3.8'

services: 
  bot: 
    build: 
      context: .
    volumes: 
      - ./:/bot
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./cogs
          target: /bot/cogs
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_pouty
      - POSTGRES_DB=botdb
    volumes:
      - postgres_data:/var/lib/postgres/data
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.0.4
    ports: 
      - 2333:2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
volumes:
  postgres_data:
